version: '3.8'
services:

  #PHP Service
  kanjabe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanjabe
    restart: always
    tty: true
    environment:
      SERVICE_NAME: kanjabe
      SERVICE_TAGS: kanjabe-dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - kanjabe-network

  #Nginx Service
  kanjabe-web-service:
    image: nginx
    container_name: kanjabe-web-service
    restart: always
    tty: true
    ports:
      - "8082:80"
      - "8442:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - kanjabe-network

  #MySQL Service
  kanjabe-db:
    image: mysql
    container_name: kanjabe-db
    restart: always
    tty: true
    ports:
      - "33062:3306"
    environment:
      MYSQL_DATABASE: kanjabe
      MYSQL_USER: kanjabe
      MYSQL_PASSWORD: kanjabe
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      SERVICE_TAGS: db-kanjabe-dev
      SERVICE_NAME: kanjabe-db
    volumes:
      - kanjabe-db:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - kanjabe-network

  #PHPMyAdmin
  db-api-iota-mgmt:
    image: phpmyadmin
    container_name: db-api-iota-mgmt
    restart: always
    ports:
      - 8083:80
    environment:
      PMA_HOST: kanjabe-db
    volumes:
      - kanjabe-dbmgmt:/var/www
    networks:
      - kanjabe-network

#Docker Networks
networks:
  kanjabe-network:
    driver: bridge
#Volumes
volumes:
  kanjabe-db:
  kanjabe-dbmgmt:
    driver: local
